steps:
- name: gcr.io/cloud-builders/gcloud
  dir: app
  args:
  - kms
  - decrypt
  - --ciphertext-file=refugee-health-alliance-hikma-fc3ea8198330.json.enc
  - --plaintext-file=refugee-health-alliance-hikma-fc3ea8198330.json
  - --location=global
  - --keyring=hikma-key
  - --key=hikma-key
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA',
          '--build-arg', 'app_env_arg=prod',
          '--build-arg', 'credential_file_arg=refugee-health-alliance-hikma-fc3ea8198330.json',
          '--build-arg', 'db_instance_arg=${_DB_INSTANCE}',
          '--build-arg', 'commit_sha_arg=$COMMIT_SHA',
          '--build-arg', 'db_password_arg=${_DB_PASSWORD}',
          '--build-arg', 'db_name_arg=${_DB_NAME}',
          '--build-arg', 'default_provider_id_arg=${_DEFAULT_PROVIDER_ID}',
          '--build-arg', 'photos_storage_bucket_arg=${_PHOTOS_STORAGE_BUCKET}',
          '--build-arg', 'exports_storage_bucket_arg=${_EXPORTS_STORAGE_BUCKET}',
          '.' ]
  dir: app
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-c', 'CLOUDSDK_CONTAINER_CLUSTER=hikma-app']
  args: ['set', 'image', 'deployment/hikma-health-backend',
          'hikma-health-backend=gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA']
images:
- 'gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA'
substitutions:
  _DB_INSTANCE: 'refugee-health-alliance-hikma:us-central1:rha-hikma'
  _DB_NAME: 'hikma_prod'
options:
  machineType: 'N1_HIGHCPU_8'
