apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-full-export
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: run-full-export
            image: gcr.io/refugee-health-alliance-hikma/hikma-health-backend:a900614191d5ac5290610671ded58530051519e4
            command:
            - /bin/bash
            - run-export.sh
          restartPolicy: OnFailure
