from events.event import Event
from admin_api.patient_data_import import PatientDataRow
import json


def get_field(data, field):
    if data.get(field) is None:
        return None
    return 'Yes' if data.get(field) else 'No'

def get_text_field(data, field, text_field):
    if data.get(field) is None:
        return None
    if data.get(field) is not None and not data.get(text_field):
        return 'Yes' if data.get(field) else 'No'
    return data.get(text_field) if data.get(field) else 'No'

def write_vitals_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.heart_rate = data.get('heartRate')
    if data.get('systolic') and data.get('diastolic'):
        row.blood_pressure = f"{data.get('systolic')}/{data.get('diastolic')}"
    row.sats = data.get('sats')
    row.temp = data.get('temp')
    row.respiratory_rate = data.get('respiratoryRate')
    row.weight = data.get('weight')
    row.blood_glucose = data.get('bloodGlucose')
    

def write_medical_hx_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.allergies = data.get('allergies')
    row.tobacco = data.get('obacco')
    row.alcohol = data.get('alcohol')
    row.drugs = data.get('drugs')
    row.surgeryHx = data.get('surgeryHx')
    row.chronicConditions = data.get('chronicConditions')
    row.currentMedications = data.get('currentMedications')
    row.vaccinations = data.get('vaccinations')
    row.cancer = data.get('cancer')
    row.cancerDetails = data.get('cancerDetails')
    row.epilepsy = data.get('epilepsy')
    row.epilepsyDetails = data.get('epilepsyDetails')
    row.heartDisease = data.get('heartDisease')
    row.heartDiseaseDetails = data.get('heartDiseaseDetails')
    row.hypertension = data.get('hypertension')
    row.hypertensionDetails = data.get('hypertensionDetails')
    row.thyroidConditions = data.get('hyroidConditions')
    row.thyroidConditionsDetails = data.get('hyroidConditionsDetails')
    row.tuberculosis = data.get('uberculosis')
    row.tuberculosisDetails = data.get('uberculosisDetails')
    row.diabetes = data.get('diabetes')
    row.diabetesDetails = data.get('diabetesDetails')
    row.multipleBirths = data.get('multipleBirths')
    row.multipleBirthsDetails = data.get('multipleBirthsDetails')
    row.breechBirths = data.get('breechBirths')
    row.breechBirthsDetails = data.get('breechBirthsDetails')
    row.domesticViolence = data.get('domesticViolence')
    row.domesticViolenceDetails = data.get('domesticViolenceDetails')
    row.alcoholismDrugAddiction = data.get('alcoholismDrugAddiction')
    row.alcoholismDrugAddictionDetails = data.get('alcoholismDrugAddictionDetails')
    row.codependency = data.get('codependency')
    row.codependencyDetails = data.get('codependencyDetails')
    row.nutritionalDisorder = data.get('nutritionalDisorder')
    row.nutritionalDisorderDetails = data.get('nutritionalDisorderDetails')
    row.abuse = data.get('abuse')
    row.abuseDetails = data.get('abuseDetails')
    row.sexualAbuse = data.get('sexualAbuse')
    row.sexualAbuseDetails = data.get('sexualAbuseDetails')
    row.mentalDisorders = data.get('mentalDisorders')
    row.mentalDisordersDetails = data.get('mentalDisordersDetails')

def write_examination_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.trauma_physical = data.get('trauma_physical')
    row.trauma_sexual = data.get('trauma_sexual')
    row.trauma_abuse = data.get('trauma_abuse')
    row.trauma_killing = data.get('trauma_killing')
    row.trauma_p_seperation = data.get('trauma_p_seperation')
    row.trauma_threats = data.get('trauma_threats')
    row.trauma_t_j = data.get('trauma_t_j')
    row.trauma_others = data.get('trauma_others')

def write_med1_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_1 = data.get('medication')
    row.type_1 = data.get('type')
    row.dosage_1 = data.get('dosage')
    row.days_1 = data.get('days')

def write_med2_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_2 = data.get('medication')
    row.type_2 = data.get('type')
    row.dosage_2 = data.get('dosage')
    row.days_2 = data.get('days')

def write_med3_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_3 = data.get('medication')
    row.type_3 = data.get('type')
    row.dosage_3 = data.get('dosage')
    row.days_3 = data.get('days')
		
def write_med4_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_4 = data.get('medication')
    row.type_4 = data.get('type')
    row.dosage_4 = data.get('dosage')
    row.days_4 = data.get('days')

def write_med5_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_5 = data.get('medication')
    row.type_5 = data.get('type')
    row.dosage_5 = data.get('dosage')
    row.days_5 = data.get('days')

def write_med_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medicationM1 = data.get('medicationM1')
    row.typeM1 = data.get('typeM1')
    row.routeM1 = data.get('routeM1')
    row.dosageM1 = data.get('dosageM1')
    row.daysM1 = data.get('daysM1')
    row.medicationM2 = data.get('medicationM2')
    row.typeM2 = data.get('typeM2')
    row.routeM2 = data.get('routeM2')
    row.dosageM2 = data.get('dosageM2')
    row.daysM2 = data.get('daysM2')
    row.medicationM3 = data.get('medicationM3')
    row.typeM3 = data.get('typeM3')
    row.routeM3 = data.get('routeM3')
    row.dosageM3 = data.get('dosageM3')
    row.daysM3 = data.get('daysM3')
    row.medicationM4 = data.get('medicationM4')
    row.typeM4 = data.get('typeM4')
    row.routeM4 = data.get('routeM4')
    row.dosageM4 = data.get('dosageM4')
    row.daysM4 = data.get('daysM4')
    row.medicationM5 = data.get('medicationM5')
    row.typeM5 = data.get('typeM5')
    row.routeM5 = data.get('routeM5')
    row.dosageM5 = data.get('dosageM5')
    row.daysM5 = data.get('daysM5')
    row.medicationM6 = data.get('medicationM6')
    row.typeM6 = data.get('typeM6')
    row.routeM6 = data.get('routeM6')
    row.dosageM6 = data.get('dosageM6')
    row.daysM6 = data.get('daysM6')
    row.medicationM7 = data.get('medicationM7')
    row.typeM7 = data.get('typeM7')
    row.routeM7 = data.get('routeM7')
    row.dosageM7 = data.get('dosageM7')
    row.daysM7 = data.get('daysM7')
    row.medicationM8 = data.get('medicationM8')
    row.typeM8 = data.get('typeM8')
    row.routeM8 = data.get('routeM8')
    row.dosageM8 = data.get('dosageM8')
    row.daysM8 = data.get('daysM8')
    row.medicationM9 = data.get('medicationM9')
    row.typeM9 = data.get('typeM9')
    row.routeM9 = data.get('routeM9')
    row.dosageM9 = data.get('dosageM9')
    row.daysM9 = data.get('daysM9')
    row.medicationM10 = data.get('medicationM10')
    row.typeM10 = data.get('typeM10')
    row.routeM10 = data.get('routeM10')
    row.dosageM10 = data.get('dosageM10')
    row.daysM10 = data.get('daysM10')

def write_physiotherapy_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.previousTreatment = data.get('previousTreatment')
    row.previousTreatmentText = data.get('previousTreatmentText')
    row.complaint = data.get('complaint')
    row.hpi = data.get('hpi')
    row.appearance = data.get('appearance')
    row.eent = data.get('eent')
    row.heartPulses = data.get('heartPulses')
    row.lungs = data.get('lungs')
    row.abdomen = data.get('abdomen')
    row.genitales = data.get('genitales')
    row.extremities = data.get('extremities')
    row.skin = data.get('skin')
    row.neuro = data.get('neuro')
    row.isPregnant = data.get('isPregnant')
    row.lastPeriodFirstDay = data.get('lastPeriodFirstDay')
    row.assessmentPlan = data.get('assessmentPlan')
    row.notes = data.get('notes')
    row.referral = data.get('referral')
    row.referralText = data.get('referralText')

def write_covid_19_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    if data.get('seekCare'):
        row.covid_19_result = 'Seek Emergency Care and Isolate'
    elif data.get('testAndIsolate'):
        row.covid_19_result = 'Test/Isolate Patient'  
    else:
        row.covid_19_result = 'No Action Necessary'    

def write_nursing_notes_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.bodyHabitus = data.get('bodyHabitus')
    row.procedures = data.get('procedures')
    row.observations = data.get('observations')

def write_mental_health_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.in_person = data.get('InPerson')
    row.tele = data.get('tele')
    row.female_only = data.get('femaleOnly')
    row.go_clinic = data.get('goClinic')
    row.mental_other = data.get('mentalOther')
    row.acupuncture = data.get('acupuncture')
    row.send_audio = data.get('sendAudio')
    row.psychiatry = data.get('psychiatry')
    row.refill = data.get('refill')
    row.taking_regularly = data.get('takingRegularly')
    row.concerns_followup = data.get('concernsFollowup')
    row.last_follow_up_date = data.get('lastFollowUpDate')
    row.feeling_nervous = data.get('feelingNervous')
    row.no_control_worrying = data.get('noControlWorrying')
    row.little_interest = data.get('littleInterest')
    row.feeling_down = data.get('feelingDown')
    row.cant_sleep = data.get('cantSleep')
    row.dont_feel_safe_living = data.get('dontFeelSafeLiving')
    row.how_you_feel = data.get('howYouFeel')
    row.child_body_feeling = data.get('childBodyFeeling')
    row.child_away_from_people = data.get('childAwayFromPeople')
    row.child_feeling_happy = data.get('childFeelingHappy')
    row.child_trouble_sleeping = data.get('childTroubleSleeping')
    row.child_hard_pay_attention = data.get('childHardPayAttention')
    row.child_feels_alone = data.get('childFeelsAlone')
    row.body_feelings = data.get('bodyFeelings')
    row.away_from_people = data.get('awayFromPeople')
    row.feeling_happy = data.get('feelingHappy')
    row.trouble_sleeping = data.get('troubleSleeping')
    row.hard_pay_attention = data.get('hardPayAttention')
    row.feel_alone = data.get('feelAlone')
    row.past_week_stress = data.get('pastWeekStress')


def write_interventions_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.resource_connection = data.get('resourceConnection')
    row.resource_connection_specify = data.get('resourceConnectionSpecify')
    row.active_listening = data.get('activeListening')
    row.psychoeducation = data.get('psychoeducation')
    row.sleep_hygiene = data.get('sleepHygiene')
    row.safe_space_imagine = data.get('safeSpaceImagine')
    row.muscle_relaxation = data.get('muscleRelaxation')
    row.behavioral_activation = data.get('behavioralActivation')
    row.grief_letter = data.get('griefLetter')
    row.changing_thoughts = data.get('changingThoughts')
    row.senses = data.get('senses')
    row.distraction_techniques = data.get('distractionTechniques')
    row.diary_yourself = data.get('diaryYourself')
    row.chair_technique = data.get('chairTechnique')
    row.build_strengths = data.get('buildStrengths')
    row.motivational_interviewing = data.get('motivationalInterviewing')
    row.diaphragmatic_breathing = data.get('diaphragmaticBreathing')
    row.safety_plan = data.get('safetyPlan')
    row.interpersonal_communication = data.get('interpersonalCommunication')
    row.prayer = data.get('prayer')
    row.supportive_people = data.get('supportivePeople')
    row.other_strategies = data.get('otherStrategies')
    row.psychiatric_medications = data.get('psychiatricMedications')


def write_common_problems_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.difficulty_eating = data.get('difficultyEating')
    row.suicidal_ideation = data.get('suicidalIdeation')
    row.difficulty_sleeping = data.get('difficultySleeping')
    row.hours_slept = data.get('hoursSlept')
    row.sleeping_night = data.get('sleepingNight')
    row.sleeping_falling = data.get('sleepingFalling')
    row.sleeping_walking = data.get('sleepingWalking')
    row.restless = data.get('restless')
    row.difficulty_stopping_worrying = data.get('difficultyStoppingWorrying')
    row.body_aches = data.get('bodyAches')
    row.body_aches_where = data.get('bodyAchesWhere')
    row.low_energy = data.get('lowEnergy')
    row.no_interest = data.get('noInterest')
    row.guilt = data.get('guilt')
    row.hopeless = data.get('hopeless')
    row.flashbacks = data.get('flashbacks')
    row.hypervigilance = data.get('hypervigilance')
    row.sad_irritable = data.get('sadIrritable')
    row.hallucinations = data.get('hallucinations')
    row.potential_diagnosis = data.get('potentialDiagnosis')
    row.other_symptom = data.get('otherSymptom')
    row.bed_wetting = data.get('bedWetting')
    row.defiant = data.get('defiant')
    row.separation_anxiety = data.get('separationAnxiety')
    row.communication_difficulties = data.get('communicationDifficulties')

def write_lab_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.dateBt1 = data.get('dateBt1')
    row.testBt1 = data.get('testBt1')
    row.resultBt1 = data.get('resultBt1')
    row.notesBt1 = data.get('notesBt1')
    row.dateBt2 = data.get('dateBt2')
    row.testBt2 = data.get('testBt2')
    row.resultBt2 = data.get('resultBt2')
    row.notesBt2 = data.get('notesBt2')
    row.dateBt3 = data.get('dateBt3')
    row.testBt3 = data.get('testBt3')
    row.resultBt3 = data.get('resultBt3')
    row.notesBt3 = data.get('notesBt3')
    row.dateBt4 = data.get('dateBt4')
    row.testBt4 = data.get('testBt4')
    row.resultBt4 = data.get('resultBt4')
    row.notesBt4 = data.get('notesBt4')
    row.dateBt5 = data.get('dateBt5')
    row.testBt5 = data.get('testBt5')
    row.resultBt5 = data.get('resultBt5')
    row.notesBt5 = data.get('notesBt5')
    row.dateI1 = data.get('dateI1')
    row.testI1 = data.get('testI1')
    row.resultI1 = data.get('resultI1')
    row.notesI1 = data.get('notesI1')
    row.dateI2 = data.get('dateI2')
    row.testI2 = data.get('testI2')
    row.resultI2 = data.get('resultI2')
    row.notesI2 = data.get('notesI2')
    row.dateI3 = data.get('dateI3')
    row.testI3 = data.get('testI3')
    row.resultI3 = data.get('resultI3')
    row.notesI3 = data.get('notesI3')